---
title: "Progress Memo 2-- Diabetes Hospitalization: Risk for Readmission"
subtitle: |
  | Final Project 
  | Data Science 2 with R (STAT 301-2)
author: "Allison Kane"
date: today

format:
  html:
    toc: true
    embed-resources: true
    
execute:
  echo: false
  warning: false

from: markdown+emoji 
reference-location: margin
citation-location: margin
---

::: {.callout-tip icon=false}

## Github Repo Link

[Allison Repo Link](https://github.com/stat301-2-2024-winter/final-project-2-akane2460)

:::

::: {.callout-note icon="false"}
## Prediction goal

The goal is to classify which diabetic patients would be readmitted to the hospital after their initial discharge. 

:::

## Data source

This dataset includes data of diabetes patients admitted to the hospital for a maximum of 2 weeks at 130 different clinical care hospitals or healthcare settings from 1999 to 2008.^[Clore, John, Cios, Krzysztof, DeShazo, Jon, and Strack, Beata. (2014). Diabetes 130-US hospitals for years 1999-2008. UCI Machine Learning Repository.[ https://doi.org/10.24432/C5230J.](https://archive.ics.uci.edu/dataset/296/diabetes+130-us+hospitals+for+years+1999-2008)]

## Data Plan

To investigate this classification problem and accurately predict which patients return to the hospital, I will examine the data as follows. I will first process and clean the data, identifying variables that are redundant or do not make sense and ensuring they are not included in the models. I will account for missingness issues as well. Then, I will process and split the data into training and testing sets. I will also create a resamples dataset using vfold for model cross-validation. Then, I will use a logistical regression style recipe and a tree-based recipe to form models. The models will include these six: logistical regression (null/baseline), lasso (applied to logistical approach), ridge (applied to logistical approach), knn nearest neighbor, random forest and gradient boosted tree. I will then assess their performance ideally using accuracy and roc_auc_curve metrics. 

# Preliminary Fits
Below are the assessments of the following models: logistical regression (with a null recipe), random forest (with a tree-based recipe).

::: {.callout-box icon=false}

## Logistical Regression

Accuracy and AUC-ROC

|.metric  |.estimator | .estimate|
|:--------|:----------|---------:|
|accuracy |binary     | 0.6132061|
|roc_auc  |binary     | 0.3479326|

Given that our accuracy measure for this model is .613 (approximately), this indicates that about 61.3% of the model's predictions are correct in determining which patients will return to the hospital after they are discharged.

Given that our ROC_AUC value is .348 (approximately), this indicates that the model is performing worse than random chance. This indicates further adjustments to obtain a more powerful predictive model.

:::

::: {.callout-box icon=false}

## Random Forest

Accuracy and AUC-ROC

To be determined.


:::

# Overall Progress, Potential Issues and Next Steps

  Overall, this progress indicates that there is much to be done. The logistical regression was fitted relatively easily, however the random forest model took considerable time and caused substantial issues in the github and the operating system of my computer, even with parallel processing. Examining how tuning and fitting the other models going forward might improve the predictive capabilities will be beneficial. Currently, I am exploring options to obtain a separate computer that has a more powerful processing capability. I intend to resolve the RStudio and GitHub issues in office hours and utilize TA/instructors to determine the scope of the problem. 
  Moving forward, it might be worthwhile to re-examine some of the recipes in order to account for further issues with interactions that were not addressed the first time. Additionally, it might be beneficial to include more specific variables in the model. The variable `change` for example was used to generally reflect changes in overall diabetes medications. However, it might lend the model more strength if we examined which specific medications would be best for predicting a patient's return to the hospital. Additionally, fits and tunings must be done for the remaining models. Specifying which parameters and hyperparameters are of greatest interest needs to be conducted. Substantial issues continue to occur with the folded resamples and it remains a major barrier to the project's completion. Feedback on how to improve recipes and model tuning process would be **greatly** appreciated, as thus far that has been the biggest struggle in moving forward the final.
  
